// Every feature and how to use it: Settings -> All features.
// [group, [[name, how], ...]]
export const FEATURES = [
  ["Tabs", [
    ["New / close / reopen tab", "Ctrl+T, Ctrl+W, Ctrl+Shift+T (also brings back a closed window)."],
    ["Switch tabs", "Ctrl+Tab / Ctrl+Shift+Tab, Ctrl+1..8, Ctrl+9 for the last one."],
    ["Tab menu", "Right-click a tab: reload, duplicate, pin, mute, sleep, group, bookmark, copy link, move, close others / left / right."],
    ["Pinned tabs", "Tab menu -> Pin tab. Icon only, in front, can't be closed by accident."],
    ["Mute a tab", "Click the speaker on the tab, or Ctrl+M."],
    ["Pick several tabs", "Ctrl+click or Shift+click tabs; the tab menu and Ctrl+W then act on all of them."],
    ["Tab groups", "Tab menu -> Add tab to new group, type a name. Click the name to fold, double-click to rename, right-click for colour, save, ungroup."],
    ["Saved groups", "Group menu -> Save group. It appears on the bookmarks bar; click it to reopen."],
    ["Group by site", "Tab menu -> Group tabs by site, or Settings -> Tabs -> Group tabs from the same site."],
    ["Tab search", "Ctrl+Shift+A or the arrow beside the tabs: every tab, sleeping and closed ones too."],
    ["Vertical tabs", "Settings -> Tabs -> Tab layout -> Side. Drag the edge to resize, the arrow collapses it."],
    ["Hover cards", "Rest the mouse on a tab: title, preview, memory. Settings -> Tabs to turn parts off."],
    ["Keep tabs when closing", "Settings -> Tabs -> Keep tabs when Kessel closes."],
    ["Sleeping / paused tabs", "Automatic for tabs you haven't used; tune in Settings -> Performance. Tab menu -> Put to sleep."],
    ["Move tabs between windows", "Drag a tab onto another window, or out of the strip for a new window; or tab menu -> Move."],
  ]],
  ["Windows", [
    ["New window", "Ctrl+N. Shift+Enter in the address bar opens it there."],
    ["Private window", "Ctrl+Shift+N. No history, no saved session, cookies forgotten."],
    ["Close window", "Ctrl+Shift+W or Alt+F4. Reopen with Ctrl+Shift+T."],
    ["Full screen", "F11."],
    ["Pop-out window", "Drag a tab below the toolbar, or tab menu -> Pop out."],
  ]],
  ["Address bar", [
    ["Go / search", "Ctrl+L, F6 or Alt+D, then type. Alt+Enter: new tab; Ctrl+Enter adds www. and .com."],
    ["Suggestions", "Appear as you type: history, bookmarks, open tabs, your search engine."],
    ["Instant answers", "Type 3*7, 5 km in miles, 20 usd in eur, define word, time in tokyo, uuid, password..."],
    ["Commands", "Type an action like clear history, private window, vertical tabs."],
    ["Search engine", "Click the arrow in the address bar, or Settings -> Search & Startup."],
    ["Share / QR code", "The share button in the address bar."],
    ["Bookmark", "Ctrl+D or the star. Ctrl+Shift+D bookmarks all tabs; Ctrl+Shift+B toggles the bar."],
  ]],
  ["Pages", [
    ["Back / forward / reload", "Alt+Left / Alt+Right, F5 or Ctrl+R; Ctrl+F5 ignores the cache; Esc stops."],
    ["Zoom", "Ctrl+Plus / Ctrl+Minus / Ctrl+0, or Ctrl+mouse wheel. Remembered per site."],
    ["Find in page", "Ctrl+F (starts with selected text), F3 / Shift+F3 for next / previous."],
    ["Print / save / source", "Ctrl+P, Ctrl+S, Ctrl+U."],
    ["Developer tools", "F12. Task manager: Shift+Esc."],
    ["Open a file", "Ctrl+O."],
    ["Links", "Ctrl+click or middle-click: new tab. Shift+click: new window."],
    ["Media controls", "The music note beside the menu, once a tab has played sound: play/pause, seek, speed, captions, audio track, picture-in-picture -- for any tab of the window."],
  ]],
  ["Your data", [
    ["History", "Ctrl+H. Search, by site, delete days or sites."],
    ["Downloads", "Ctrl+J, or the rail's download button."],
    ["Passwords", "Ctrl+Shift+L or the rail's key. Autofill offers saved logins."],
    ["Clear browsing data", "Ctrl+Shift+Delete."],
    ["Accounts", "The person button in the address bar: be signed in as several people at once."],
    ["Import", "Settings -> Import, from Chrome, Opera, Opera GX, Brave."],
  ]],
  ["Kessel", [
    ["Menu", "Alt+F, F10 or the dots at the top right."],
    ["Shields (ad blocking)", "The shield in the address bar or on the rail."],
    ["Sidebar sites", "Tab menu -> Add to sidebar, or the + on the rail."],
    ["Your own shortcuts", "Settings -> Keyboard & Mouse."],
    ["Look", "Settings -> Appearance: theme, Liquid Glass, wallpaper, bookmarks bar."],
    ["Help", "F1: shortcuts and tips."],
    ["Hardware acceleration", "Settings -> Performance: on or off, and which graphics card. kessel://gpu shows what the graphics card does and which video formats play."],
  ]],
];
